### ISSUE TITLE
Masking using Scene classification layer

### ISSUE THREAD

**Issue by orianif** [EOA-team/eodal#77] opened 2023-09-18 11:52 UTC
**Describe the bug**
Some Sentinel-2 scenes do not get masked properly using the mask_clouds_and_shadows()  in preprocess_sentinel2_scenes().
See the attached example code, where class 9 is specified for masking but it remains unmasked in the image. So far I observed it in images with a specific partial tile coverage.

**To Reproduce**
Run the example code in :
[masking_problem.zip](https://github.com/EOA-team/eodal/files/12647411/masking_problem.zip)

**Comment by lukasValentin** [comment] 2023-09-18 14:10
Hi @orianif, the problem is not really related to EOdal - it is related to the way you interpolate the data into the grid by your custom function `scene_to_array(sc,tx,ty)`. When you have a closer look to line 133
```python
Gv = np.copy(band.values.data)
```
you can see that you only interpolate the `data`  part of the masked array but not the mask (which would be `band.values.mask`).

A correct implementation of said function which also considers the `mask` part would be

```python
def scene_to_array(sc,tx,ty):
    """
    Generate an numpy array (image stack) from a given Eodal SceneCollection.
    The scenes are resampled on a costant coordinate grid allowing pixel analysis.
    Missing data location are marked as nans.
    
    Parameters
    ----------
    sc : Eodal SceneCollection
        The given Scene Collection generated from Eodal
    tx : Float Vector
        x coordinate vector for the resample grid.
    ty : Float Vector
        x coordinate vector for the resample grid.

    Returns
    -------
    im : float 4D numpy array.
        Array containing the stack of all scenes.
        4 dimensions: [x, y, bands, scenes]

    """
    
    ts = sc.timestamps # time stamps for each image
    bands = sc[sc.timestamps[0]].band_names # bands
    im_size = [len(ty),len(tx)] # image size
    im = np.empty(np.hstack([im_size,len(bands),len(ts)])) # preallocate matrix

    for i, scene_iterator in enumerate(sc):
        
        # REGRID SCENE TO BBOX AND TARGET RESOLUTION
        scene = scene_iterator[1]        
        for idx, band_iterator in enumerate(scene):
            
            #original grid coordinates
             band = band_iterator[1]
             Gv = np.copy(band.values.data)
             Mv = np.copy(band.values.mask)
             ny,nx = np.shape(Gv)
             vx = band.coordinates['x']
             vy = band.coordinates['y']
            
             # create interpolator
             Gv_no_nans = Gv.copy()
             Gv_no_nans[np.isnan(Gv)] = 0
             f = interp2d(vx,vy,Gv_no_nans,kind='linear',fill_value=0)
             m = interp2d(vx,vy,Mv,kind='linear',fill_value=1)
             
             # interpolate band on the target grid
             Tv = np.flipud(f(tx,ty))
             Tmv = np.flipud(m(tx,ty))
             
              # assign interpolated band [i = scene , b = band]
             im[:,:,idx,i] = np.ma.masked_array(Tv,Tmv)
    
    return im
```

There is also a `DeprecationWarning` raised by `scipy`:

```bash
<string>:1: DeprecationWarning:         `interp2d` is deprecated!
        `interp2d` is deprecated in SciPy 1.10 and will be removed in SciPy 1.13.0.

        For legacy code, nearly bug-for-bug compatible replacements are
        `RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
        scattered 2D data.

        In new code, for regular grids use `RegularGridInterpolator` instead.
        For scattered data, prefer `LinearNDInterpolator` or
        `CloughTocher2DInterpolator`.

        For more details see
        `https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html`
```
but I leave this to you to fix it ;)

**Comment by orianif** [comment] 2023-09-20 15:27
Hi Lukas,

Thank you so much for your help. I see how I could correct the function scene_to_array(sc,tx,ty).
Still, if I take away that function and just show the band data alongside their masks, straight from the mapper, the data look to be masked, but the mask does not correspond. And this behavior is not consistent with all tiles, apparently.
See the attached example.

[masking_problem_2.zip](https://github.com/EOA-team/eodal/files/12674838/masking_problem_2.zip)

**Comment by lukasValentin** [comment] 2023-09-20 18:21
Dear @orianif ,

thanks for bringing this up.

I let run your script and visualized the scene using a very ugly nodata color to see if the masking worked (added within the for loop in L152):

```python
scene = scene_iterator[1]
f, ax = plt.subplots(1, 2, figsize=(15, 15))
scene.plot_multiple_bands(['red', 'green', 'blue'], ax=ax[0], nodata_color='red')
scene.plot_band('SCL', ax=ax[1], colormap='tab20b')
```

By comparing the RGB image (nodata and masked values are colored red) with the scene classification, all classes you asked for seem to have been masked:


![eodal_debug_example1](https://github.com/EOA-team/eodal/assets/30413792/0f65da8a-466f-4ae5-b868-2945b8a76da7)

When plotting a single band, only, I get the following result:

```python
scene.plot_band('blue')
```
![eodal_debug_example2](https://github.com/EOA-team/eodal/assets/30413792/88cfde9f-1ff0-475c-9d04-4a9c2e2b5b39)

Here, the "masked" values are actually set to no-data (which is 0, i.e., the default for Sentinel-2 images) as you can see by comparing the grey-scale image with the RGB visualization. I acknowledge that this behavior is confusing and should be corrected. The correct behavior would be to see the original values in the `data` part of the array but the mask should flag those pixels. Instead, the "masked" pixels are no-data.

The reason for that behavior is either related to the merging function (we have multiple S2 tiles involved) or the internal reprojection of the scene onto a common spatial extent.

 - see [here](https://github.com/EOA-team/eodal/blob/371aeaca9899d0140378325e4f68b676998811f9/eodal/core/algorithms.py#L59) for the merging logic
 -  or [here](https://github.com/EOA-team/eodal/blob/239fa0d2c8ac2fd5810853109cdf7225500b3f89/eodal/mapper/mapper.py#L726) for the  scene reprojectiononto the common bounding box of the SceneCollection.
 
 My suspicion is actually more related to latter, which would mean there is a potential bug in [eodal.core.band.reproject](https://github.com/EOA-team/eodal/blob/239fa0d2c8ac2fd5810853109cdf7225500b3f89/eodal/core/band.py#L1921). 

However,  I need to debug this issue further to understand better what is going on.

For the time being, a solution would be to move the `scene.mask_clouds_and_shadows()` call outside of the pre-processing function and simply call in the for-loop in L152ff.

**Comment by orianif** [comment] 2023-09-21 08:46
Hi Lukas,

Thank you for advancing on that, it is not so bad if we get zeros for masked data, but check out the following when you have time. 

Rastercolleciton.plot() works, but I observe an apparently inconsistent behavior in the raw data extracted from the RasterCollection object. With query dates:

```
time_start: datetime = datetime(2017,6,13) 
time_end: datetime = datetime(2017,6,13)
```   

plotting the blue raw data values and their mask:

```
for i, scene_iterator in enumerate(mapper.data):
    scene = scene_iterator[1]        
    #original grid coordinates
    band = scene['blue']
    plt.figure()
    plt.subplot(1,2,1)
    band.values.data[band.values.data==0]=np.nan
    plt.imshow(np.copy(band.values.data),interpolation='None')
    plt.subplot(1,2,2)
    plt.imshow(np.copy(band.values.mask),interpolation='None')


```
I get this:
![image](https://github.com/EOA-team/eodal/assets/36014536/902ac255-657e-412e-8a12-3adb0404e7e0)

 band.values.data is masked, but the band.values.mask is not the actual mask.
While, if you change the query dates to:

```
time_start: datetime = datetime(2017,7,30) 
time_end: datetime = datetime(2017,8,1)  
```

with the same plotting code, band.values.mask appears as the actual mask, but band.values.data is not masked:

![image](https://github.com/EOA-team/eodal/assets/36014536/673148a5-e8c1-432c-bd14-23be905d0d00)

Where am I doing wrong?

Thanks,
Fabio

**Comment by lukasValentin** [comment] 2023-09-21 16:50
Hi @orianif,

I don't think you are doing anything wrong. The reason why the result on `datetime(2017,7,30) `  has a correct mask while for the first date it hasn't, has to do with the way EOdal treats the need to merge data from different tiles. Apparently, something has been messed up and I have to figure out why. So no need to change your code, we have to fix it in EOdal.

Hope that helps for the time being!

**Comment by lukasValentin** [comment] 2023-10-06 08:12
Hi @orianif,

I found now some time to debug `EOdal` and fixed several smaller things that might be relevant for this issue:

* the `fill_value` of the masked parts of the array (relevant for writing data to file) was not always handled correctly meaning that numpy inferred a fil value. This fill value, however, did not necessary match the `nodata` value as it actually should. Now, it should be ensure that `fill_value` equals the `nodata` value.
* The propagation of the `fill_value` in `Band.resample` and `Band.reproject` has been fixed, which was not properly handled before.
* when writing datasets the data type checking did not work properly meaning that integer datasets with two different integer data types (e.g., `uint8` and `uint16`) were always cast to `float32`, which is unnecessary and increases disk space consumption. This issue has been fixed by a generic type checking function that now supports all numpy `int`, `uint`, `float`, and `complex` data types. The previous behavior also meant that the `nodata` value reported in the file metadata and the actual (but then unrecognized) nodata value in the raster data did not match causing undesired behavior when visualizing data.
* in the `merge` algorithms the recreation of the mask from nodata was missing. It should now work given that masked values were set to nodata (see the previous point), and the correct nodata value is written to the metadata.

Could you please check @orianif if these fixes solve your problem?
You can install a dev version of EOdal by running

```
pip uninstall eodal -y
pip install git+https://github.com/lukasValentin/eodal@dev
```

Please let me know if your issue is resolved.

**Comment by orianif** [comment] 2023-11-09 10:28
Hi Lukas,

Thank you so much for your efforts. I still experience the problem (masking inconsistency) after:

```
pip uninstall eodal -y
pip install git+https://github.com/lukasValentin/eodal@dev
```

The workaround you proposed, to get consistent masking on the band values, still works:

...
    band.values.data[band.values.mask==1]=0
...

I remain available for any further testing.

Best,
Fabio

**Comment by lukasValentin** [comment] 2023-11-15 13:50
Hi @orianif, I'm not sure if I fully understand. Do you have a minimum reproducible code example for reproducing the plots above and showing what exactly the issue is?

**Comment by lukasValentin** [comment] 2023-11-24 12:26
Hi @orianif,

I think there is a bit of a misunderstanding how numpy masked arrays work. Let's have a deeper look to explain why the results seem "inconsistent":

What's going on in the first case (`2017-06-13`) is the fact that mosaicing is involved; that's the reason why masked values are set to 0 (nodata) as this is the way `rasterio`  handles masked pixels when writing raster datasets (for mosaicing we have to write raster datasets to disk temporarily to avoid memory issues). In fact, the `band.values.data` returns `nodata` for all masked points but that's just because of rasterio. So it might seem, the masked array works "extra-ordinary" in this case but it actually does not.

In the second case (`2017-07-31`) no mosaicing is required and therefore the original pixel values are still preserved in `data`. Numpy masked arrays do not alter the pixel values - they only come with a boolean mask that is used by numpy internally to correctly figuring what to do (or not to do) with a pixel depending on the corresponding mask value. The second case is therefore the same as the first case. The only difference is that there was no rasterio involved (yet), therefore there are no `nodata` pixel values.

However, since the mask is correct - as you also pointed out - in both cases, there is nothing wrong. As long as you stick with numpy.ma.maskedArrays, the results will be always consistent (note: when accessing `data` directly you are leaving this world). Simply put, EOdal is doing exactly what it's supposed to do as `plt.imshow` shows:

```python
plt.imshow(band.values)
```
![20170731](https://github.com/EOA-team/eodal/assets/30413792/9b265efe-a142-44b7-bdb3-1f9d8c06e167)

I therefore close this issue as completed. In your code, I strongly advice you to either stick to `np.ma.maskedArray` or use the "work-around" that actually is just a way to convert a masked array to `ndarray` in such a way that masked pixels are set to no-data. Note that this can be also written as

```python
ndarray = band.values.filled(band.nodata)
```

**Closed by lukasValentin** 2023-11-24 12:26 UTC
Labels: bug
